### ISSUE TITLE
Migration of the Analysis scripts

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/GRAPHnetEpiApp#1]
Select from the GitLab repo, the scripts that will produce the figure which will be integrated in the app.
Later we will have to adapt them to load the data from the Database and not from the CSVs.

Important: **Do not add CSV or other datafiles to this repository**

**Comment by dcpcamara** [comment]
@fccoelho just to inform that I've selected the script (weekly analysis integrated with the fauxLL). Should I make a merge request in here?

**Comment by fccoelho** [comment]
since we are simply migrating code, you can push straight into master.
please create a subdirectory called scripts inside shinyapp.

Em ter, 6 de out de 2020 15:39, Daniel C. P. Câmara <
notifications@github.com> escreveu:

**Comment by fccoelho** [comment]
@dcpcamara: Are there any more files needing migration? if not, please close this issue

**Comment by dcpcamara** [comment]
No, all figures and maps are inserted inside this one script. I'll close it now.
