### ISSUE TITLE
align the three boxes on the home page on the same period.

### ISSUE THREAD

**Issue by bwicht** [thegraphnetwork/GRAPHnetEpiApp#24]
In the boxes that present the overall situation, have the boxes displaying the same period, either 1 month, 2 weeks or else. Can also have rows for each period.

**Comment by lbianchi** [comment]
Do you mean that we should have a select input for date similar to the one that we have for countries?

**Comment by lbianchi** [comment]
I guess I got this done by adding the calendar function, right? I am closing the issue, but feel free to reopen if still needed.
