### ISSUE TITLE
import data into Postgres

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/GRAPHnetEpiApp#3]
In order to migrate to using a database in the backend, we need to load the data into the database. For this, we will need to design the data model (tables and relationships). This will be detailed on another issue

**Comment by fccoelho** [comment]
Import script started in aea8655

**Comment by fccoelho** [comment]
@JyotiDalal93  and @Anjali0296 see if you can load all the scripts with this `loaddata.py` script, the CSV from Liberia seem to have issues.
the code for inserting the data into the db is not there yet, because we should first test the reading of all the CSVs and make sure we have no parsing errors
```bash
docker-compose -p shinyapp -f docker-compose.yml --env-file .env_db up --build
```
and connect with the database.

**Comment by JyotiDalal93** [comment]
Hi @fccoelho! I just added a unique constraint to avoid duplicates in the table 'line_list'. I have used the columns namely 'patinfo_id', 'report_date', 'patinfo_ageonset_years', 'patinfo_sex', 'patinfo_resadmin1', and 'patinfo_resadmin2' for this. Kindly have a look, thank you.

**Comment by fccoelho** [comment]
thank you @JyotiDalal93

**Comment by fccoelho** [comment]
This issue is done. The current version of the script fixed some type issues in the CSVs. But Ideally the CSV must be fully clean before loading.
