### ISSUE TITLE
Design the relational model

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/GRAPHnetEpiApp#4]
Design and create the database initially by defining the physical model [in this document](https://my.vertabelo.com/doc/YTV1EHVPPk2jHUUTTqnC4dpM9Rjrjfu4).

**Comment by fccoelho** [comment]
Hi @JyotiDalal93  I am starting to design the relational data model, tables and their relations. For this I am using Vertabello (see link in the description of this issue. I would like you to help me with it. First check if you can access the document I linked above, and see if you have permission to edit (let me know if you don't). Then you can start by completing the columns on the table `line_list`.

Vertabello's interface is pretty intuitive , you just select the table and click on ad collumn on the right panel:
![image](https://user-images.githubusercontent.com/140123/94933190-72aab280-04a0-11eb-8a93-774ead420f36.png)
You can follow the columns present on the Cleaned line lists CSVs.

**Comment by JyotiDalal93** [comment]
Hey @fccoelho! Yes, I am able to access the document you linked above, and I do have the permission to edit it. I will start completing the columns on the table 'line_list' very soon. Thank you.

**Comment by fccoelho** [comment]
Hi @JyotiDalal93 have you made some progress with it?

**Comment by JyotiDalal93** [comment]
Hi @fccoelho! Not yet, I am really sorry about it. I was pretty much occupied with the monthly report of Sao Tome Principe and Seychelles.  Will make some progress today (for sure). I will get in touch with you in case I will have any questions. Thank you.

**Comment by JyotiDalal93** [comment]
Hi @fccoelho! I am mostly done with creating a table namely 'line_list', please have a look. It has something around 60 columns (following the clean CSV format). But, do we actually need these many columns? I mean, we usually require a small subset of columns for doing the analysis. 
Kindly let me know what I should be doing next, thank you.

**Comment by fccoelho** [comment]
Hi Jyoti I think you are editing a different document than the one I sent originally! :-D I sent you an invitation to edit my document.

I think you will be able to copy and paste the table you have created to the project I am editing.

About the columns, there are two ways to solve this: we may filter out the columns before we import the CSVs into the database, or we just add all columns and import everything, even though we may not use them. The second one is more future-proof, because we may decide to use additional columns in the future.

**Comment by fccoelho** [comment]
Thank you  @JyotiDalal93  next step will be to test load the CSV in the database. Closing this issue and will start new ones with the next steps
