### ISSUE TITLE
Add Unique constraint to line_list table

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/GRAPHnetEpiApp#9]
the line_list needs an [unique constraint](https://www.postgresql.org/docs/13/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS) to avoid the insertion of duplicate lines. we need to choose a set of fields (columns) to use to characterize uniqueness, i.e., if these fields are the same in two lines they should be considered duplicates

**Comment by JyotiDalal93** [comment]
Hi @fccoelho! Sure, thank you. 

In the table I created, 'patinfo_ID' is a primary key. Also, I am not sure whether we can use other columns to characterize uniqueness.

**Comment by fccoelho** [comment]
We should use a small set of columns to define uniqueness. maybe 3 or four will suffice, no need for them to be primary keys. They should be columns associated with the identification of the patient and not very likely to contain errors, otherwise, a mere misspelling in one of the fields would allow for duplicate lines.

**Comment by fccoelho** [comment]
Thank you @JyotiDalal93
